### ISSUE TITLE
Error when handling a pull request containing file deletion

### ISSUE THREAD

**Issue by yangl1996** [yangl1996/docs-toolchain#18]
```
error: docs/x.md: No such file or directory
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "github.py", line 98, in handle_pull_request
    output_format="html5")
  File "/usr/local/lib/python3.4/dist-packages/markdown/__init__.py", line 529, in markdownFromFile
    kwargs.get('encoding', None))
  File "/usr/local/lib/python3.4/dist-packages/markdown/__init__.py", line 428, in convertFile
    input_file = codecs.open(input, mode="r", encoding=encoding)
  File "/usr/lib/python3.4/codecs.py", line 896, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/root/test-centos-docs/docs/x.md'
```

The program can't find the file to build.

**Comment by kunaaljain** [comment]
Fixed in #19
